fluid-project/infusion

src/framework/core/js/Fluid.js
tests/framework-tests/core/js/ModelTransformationTests.js

Removed the incorrect comment about termination from fluid.each. Also addressed a linting issue.
http://issues.fluidproject.org/browse/FLUID-5591

FLUID-5591: Removed erroneous comment

---

README.md
ReleaseNotes.md
demos/overviewPanel/index.html
src/components/overviewPanel/js/OverviewPanel.js

@jobara, could you have a look at this?

FLUID-5595: Fix links to fluidproject.org site

---

src/components/tooltip/js/Tooltip.js

Updated the component to be a viewRelay compnonent.
http://issues.fluidproject.org/browse/FLUID-5606
There were several TODO's scattered throughout the code that haven't yet been addressed. Those should be taken care of as part of http://issues.fluidproject.org/browse/FLUID-5607

FLUID-5606: Updated to be a relay component

---

demos/reorderer/imageReorderer/json/config.json

FLUID-5647: Updating Image Reorderer demo's API link to new docs

---

src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

To find the index of the given value in an array.

FLUID-5657: Added fluid.transforms.indexOf

---

src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

"fluid.transforms.dereference" is the invertible partner of "fluid.transforms.indexOf".
@amb26, can you take a look? Thanks.

FLUID-5657: Added "fluid.transforms.dereference"

---

src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
tests/framework-tests/core/html/DataBinding-test.html
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidJSTests.js

This resolves the relay issue you encountered with the language panel yesterday, @cindyli

FLUID-5659: Fix for relay saturation issue in multiple relay - new core utility fluid.flatten

---

src/framework/core/js/FluidPromises.js
tests/framework-tests/core/js/FluidPromisesTests.js

as well as fluid.toPromise utility

FLUID-5584: Implemented "accumulateRejectionReason" inverse API for promises

---

src/components/textToSpeech/js/TextToSpeech.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js
tests/framework-tests/preferences/js/SelfVoicingEnactorTests.js

http://issues.fluidproject.org/browse/FLUID-5670

FLUID-5670: Moved utteranceOpts into the model

---

src/components/tableOfContents/html/TableOfContents.html

Just changed TOC to h2 heading. Preferences editor already had a h1 heading

FLUID-5679: Changed TOC heading to h2

---

tests/component-tests/tableOfContents/js/TableOfContentsTests.js

Fixed the unit test to find the h2 heading
https://issues.fluidproject.org/browse/FLUID-5679

FLUID-5679: Fixed TOC header unit test

---

.npmignore

Removed ant related files that no longer exist, also ignoring the preferences framework.
http://issues.fluidproject.org/browse/FLUID-5458

FLUID-5458: Updated npmignore (for master)

---

src/framework/core/js/Fluid.js
src/framework/core/js/jquery.standalone.js
tests/all-tests.html
tests/framework-tests/core/all-tests.html
tests/framework-tests/core/html/WebWorker-test.html
tests/framework-tests/core/js/WebWorkerTests-Worker.js
tests/framework-tests/core/js/WebWorkerTests.js

This pull request includes a basic unit test that at least verifies that a) Infusion is correctly evaluated within a Web Worker and b) that a component can be instantiated correctly and the response from an invoker sent as a message back to the main thread.

FLUID-5711: Softens references to "window" for use within Workers.

---

ReleaseNotes.md
src/framework/core/js/DataBinding.js

extra comment in DataBinding - 
@acheetham  or @colinbdclark  , perhaps?

FLUID-5249: Updated release notes for 2.0.0-beta.1 and 1.9

---

src/components/textToSpeech/js/MockTTS.js
tests/component-tests/tooltip/js/TooltipTests.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/enhancement/js/ContextAwarenessTests.js

@amb26, can you review this pull request? Thanks.

FLUID-5765: Remove the use of "autoInit".

---

README.md

https://issues.fluidproject.org/browse/FLUID-5787

FLUID-5787: Correct header syntax

---

tests/test-core/testTests/js/TestingTests.js
tests/test-core/utils/js/IoCTestUtils.js

FLUID-5583: Fix and test case for failure to boil single argument for IoC testing listener

---

README.md
src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
tests/component-tests/progress/js/ProgressTests.js
tests/test-core/jqUnit/js/jqUnit-browser.js
tests/test-core/jqUnit/js/jqUnit.js

in previous FLUID-5749 fix, updates to some comments

FLUID-5749: Fix for blunder in implementation of assertNotEquals 

---

src/framework/core/js/FluidIoC.js
tests/framework-tests/core/js/FluidIoCTests.js

FLUID-5758: Fix and test case for failure to resolve {arguments} within listener's expander

---

src/framework/core/js/FluidDocument.js
src/framework/core/js/FluidView.js
tests/all-tests.html
tests/component-tests/textfieldSlider/html/TextfieldSlider-test.html
tests/component-tests/textfieldSlider/js/TextfieldSliderTests.js
tests/framework-tests/core/all-tests.html
tests/framework-tests/core/html/FluidDocument-test.html
tests/framework-tests/core/js/FluidDocumentTests.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/renderer/js/RendererTests.js
tests/framework-tests/renderer/js/RendererUtilitiesTests.js
tests/test-core/testTests/js/TestingTests.js

It sets the value to a DOM node and fires the change event.
@amb26, can you review this pull request? Thanks.

FLUID-5666: Added a new function fluid.changeElementValue() into FluidDocument.js

---

examples/framework/preferences/minimalEditor/README.md
examples/framework/preferences/minimalEditor/css/style.css
examples/framework/preferences/minimalEditor/html/autoPilot.html
examples/framework/preferences/minimalEditor/html/heatedSeats.html
examples/framework/preferences/minimalEditor/html/minEditor.html
examples/framework/preferences/minimalEditor/html/prefsEditorTemplate.html
examples/framework/preferences/minimalEditor/index.html
examples/framework/preferences/minimalEditor/js/minEditor.js
examples/framework/preferences/minimalEditor/js/prefsEditor.js
examples/framework/preferences/minimalEditor/schemas/auxiliary.js
examples/framework/preferences/minimalEditor/schemas/primary.js

@jobara, could you have a look at this, with an eye to it being an exemplar of both Infusion/Prefs Framework best practices and simplicity?

FLUID-5754: First pass at a minimal preferences editor

---

examples/framework/preferences/minimalEditor/js/prefsEditor.js
src/framework/preferences/js/Builder.js
src/framework/preferences/js/Store.js
tests/framework-tests/preferences/js/BuilderTests.js
tests/framework-tests/preferences/js/PrefsEditorTestsCommon.js

@acheetham - here's the fix for the "storeType" issue we discussed earlier

FLUID-5831: Corrected broadcast of storeType so that it properly displaces default and test grades

---

src/framework/core/js/FluidIoC.js
src/framework/enhancement/js/ContextAwareness.js
src/framework/preferences/js/FullPreviewPrefsEditor.js
tests/framework-tests/core/js/FluidIoCTests.js

sources before raw dynamic sources, as well as base grades of non-dynamic sources before bases of dynamic sources

FLUID-5615: Improved support for acquiring grades from plain dynamic sources

---

examples/framework/preferences/minimalEditor/js/prefsEditor.js
package.json
src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
src/module/fluid.js
src/module/module.js
tests/framework-tests/core/js/FluidIoCTests.js
tests/node-tests/basic-node-tests.js
tests/test-core/utils/js/IoCTestUtils.js

FLUID-5818: Fix for failure of ginger reference from constructed child of unconstructed parent

---

src/components/uploader/js/FileQueueView.js
src/framework/core/js/FluidView.js
src/framework/renderer/js/RendererUtilities.js
tests/component-tests/uploader/js/FileQueueViewTests.js
tests/framework-tests/core/js/FluidViewTests.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/preferences/js/SelfVoicingPanelTests.js

FLUID-5821: Fixed DOM binder semantic for consistency when locating missing selectors

---

tests/component-tests/reorderer/js/LayoutReordererTests.js

@gtirloni - I've hacked these tests to accept the variant order that you are seeing - which seems quicker than trying to debug the real issue for now. Could you test out this branch to see if this test is passing for you now?

FLUID-5859: Hacking layout reorderer tests to accept variant order seen on Linux (Fedora)

---

src/framework/preferences/css/stylus/SeparatedPanelPrefsEditor.styl
src/framework/preferences/css/stylus/utils/Themes.styl

Shadow Bug fix for the bug: The shadow effect around the hide/show
preferences tab should change colour with the contrast theme.

FLUID-4991: The shadow effect around the hide/show preferences bug fix

---

src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
tests/framework-tests/core/js/DataBindingTests.js

and rewriting test case to demonstrate that it is unnecessary

FLUID-5866: Removing implementation of "fluid.priorityHolder"

---

src/framework/core/js/FluidIoC.js
tests/framework-tests/core/js/FluidIoCTests.js

to dynamic component with options given by single string reference

FLUID-5893: Fix and test case for failure to apply dynamic grades

---

src/components/inlineEdit/js/InlineEdit.js
src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
src/framework/preferences/js/Panels.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidIoCTests.js
tests/framework-tests/core/js/FluidJSTests.js
tests/test-core/utils/js/IoCTestUtils.js

simplification and correction of grade merging algorithm

FLUID-5887: Resolution and checks for double initialisation of model machinery

---

src/components/uploader/js/UploaderCompatibility-Infusion1.2.js
src/framework/core/js/ModelTransformation.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/ModelTransformationTests.js

inputPath/input is now validated on every standardInputTransform. Completed rename of transform -> transformer which had been partway done in transformer.

FLUID-5907: Fixes for regressions in Model Transformations

---

src/components/textfieldSlider/js/TextfieldSlider.js
tests/framework-tests/preferences/js/FullPreviewPrefsEditorTests.js

Fixed an issue where the native sliders in Firefox would not initialize with the correct value.
Also fixed a linting issue.
https://issues.fluidproject.org/browse/FLUID-5924

FLUID-5924: Fixed native sliders in Firefox

---

tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js

https://issues.fluidproject.org/browse/FLUID-5942

FLUID-5942: Only comparing URL of contexts

---

src/framework/preferences/css/stylus/utils/Helpers.styl

https://issues.fluidproject.org/browse/FLUID-5946

FLUID-5946: Removed redundant ";"

---

demos/reorderer/gridReorderer/css/gridReorderer.css

https://issues.fluidproject.org/browse/FLUID-5728

FLUID-5728: Adjusting Drop Marker to no push items to next row

---

src/framework/core/js/FluidIoC.js
tests/framework-tests/core/js/FluidIoCTests.js

Documentation pull request: https://github.com/fluid-project/infusion-docs/pull/100

GPII-1680: Add fluid.componentForPath()

---

tests/framework-tests/renderer/js/RendererTests.js

https://issues.fluidproject.org/browse/FLUID-5956

FLUID-5956: Convering the Renderer Performance Test to be async

---

Vagrantfile

To test, retrieve this PR and run:
```
vagrant up
grunt tests
```

FLUID-5922 - Upgrade to Fedora 24

---

ReleaseNotes.md
examples/framework/preferences/shared/html/SeparatedPanelPrefsEditorFrame-jQueryUI.html
src/lib/normalize/css/normalize.css

Upgrading to normalize.css v4.1.1
https://issues.fluidproject.org/browse/FLUID-5961

FLUID-5961: Normalize.css v4.1.1

---

demos/reorderer/gridReorderer/index.html
demos/reorderer/imageReorderer/index.html
demos/reorderer/layoutReorderer/index.html
demos/reorderer/listReorderer/index.html
examples/components/reorderer/tableRow/index.html
src/components/reorderer/reordererDependencies.json
tests/manual-tests/components/reorderer/dynamic/index.html
tests/manual-tests/framework/preferences/fullPage-schema/index-nativeHTML.html
tests/manual-tests/framework/preferences/fullPage/index-nativeHTML.html

Using touchPunch to map touch events to mouse events.
https://issues.fluidproject.org/browse/FLUID-5042

FLUID-5042: Enabling drag&drop for reorderer with touch

---

src/framework/core/js/FluidIoC.js
tests/framework-tests/core/js/FluidIoCTests.js

Depends on https://github.com/fluid-project/infusion/pull/730

FLUID-5925: Tests to confirm non-existence of FLUID-5925

---

src/framework/preferences/css/stylus/PrefsEditor.styl
src/framework/preferences/html/PrefsEditorTemplate-contrast.html

Addresses https://issues.fluidproject.org/browse/FLUID-6020
Tagging @jobara

FLUID-6020: implement fieldset wrapping of contrast options.

---

tests/component-tests/uploader/js/FileQueueViewTests.js

https://issues.fluidproject.org/browse/FLUID-6025

FLUID-6025: Updated tests

---

src/components/uploader/css/Uploader.css
src/components/uploader/html/Uploader.html

NOTE: the file queue header now scrolls with the queue of files.
https://issues.fluidproject.org/browse/FLUID-6028

FLUID-6028: Merged file queue tables into a single table

---

src/components/uploader/js/FileQueueView.js
tests/component-tests/uploader/js/FileQueueViewTests.js

https://issues.fluidproject.org/browse/FLUID-6038

FLUID-6038: Disable remove file button for uploaded files

---

Gruntfile.js

https://issues.fluidproject.org/browse/FLUID-6071

FLUID-6071: Fix stylus generation for builds

---

examples/framework/preferences/minimalFootprint/README.md
examples/framework/preferences/minimalFootprint/css/prefsEditorFullPage.css
examples/framework/preferences/minimalFootprint/css/style.css
examples/framework/preferences/minimalFootprint/fullPage.html
examples/framework/preferences/minimalFootprint/html/prefsEditorPreview.html
examples/framework/preferences/minimalFootprint/index.html
examples/framework/preferences/minimalFootprint/js/lazyLoad.js
examples/framework/preferences/minimalFootprint/js/loadScripts.js

Example code for https://github.com/fluid-project/infusion-docs/pull/95
https://issues.fluidproject.org/browse/FLUID-5943

FLUID-5943: Minimal Footprint Prefs Framework Example

---

README.md
ReleaseNotes.md

https://issues.fluidproject.org/browse/FLUID-5944

FLUID-5944: Updating the README and ReleaseNotes for the Infusion 2.0 release

---

ReleaseNotes.txt
build-scripts/build.properties
pom.xml
project.xml
src/webapp/framework/core/js/Fluid.js
src/webapp/tests/manual-tests/html/versioning.html

Updates for the 1.4.1 release
https://issues.fluidproject.org/browse/FLUID-6089

FLUID-6089: Updating release notes and version numbers to 1.4.1 

---

tests/test-core/testTests/js/IoCTestingTests.js
tests/test-core/utils/js/IoCTestUtils.js

Clean version of https://github.com/fluid-project/infusion/pull/795

FLUID-6092: Renamed "elements" to "sequenceElements" in IoC Testing Framework

---

ReleaseNotes.md

https://issues.fluidproject.org/browse/FLUID-6105

FLUID-6105: Cleaned up release notes

---

src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

https://issues.fluidproject.org/browse/FLUID-6120

FLUID-6120: Added an inverse rule for fluid.transforms.limitRange

---

tests/manual-tests/components/reorderer/dynamic/css/reorderer.css

added styling for fl-reorder-dropMarker which was missing.

FLUID-5430: in manual-page reordering test, show drop target

---

src/framework/core/js/Fluid.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/FluidJSTests.js
tests/framework-tests/core/js/ModelTransformationTests.js

https://issues.fluidproject.org/browse/FLUID-6125
Related Docs PR: https://github.com/fluid-project/infusion-docs/pull/116

FLUID-6125: Updates the numberToString transform to provide a scale option for rounding to decimal places.

---

package.json
src/module/fluid.js
src/module/module.js

@the-t-in-rtf - this is a trial fix with some extra diagnostics in - I seemed to be able to use it to run your FLUID-6139, please try it out and see if it works for you - cheers!

FLUID-6140: Improvements to Infusion's auto-self-deduping to allow it to function as a dependency of one of its own devDependencies

---

src/framework/preferences/css/stylus/SeparatedPanelPrefsEditorFrame.styl

https://issues.fluidproject.org/browse/FLUID-6153

FLUID-6153: Removing scrollbars from descriptions

---

.npmignore

https://issues.fluidproject.org/browse/FLUID-6159

FLUID-6159: Adding .vagrant to .npmignore

---

src/framework/preferences/html/PrefsEditorTemplate-contrast.html
src/framework/preferences/js/Panels.js
src/framework/preferences/messages/contrast.json
tests/framework-tests/preferences/js/PanelsTests.js

https://issues.fluidproject.org/browse/FLUID-6166
Open to suggestions about what to call the new base grade. ( See: [Channel Conversation](https://botbot.me/freenode/fluid-design/2017-07-06/?msg=88229730&page=1) )

FLUID-6166: Refactoring out a base grade for styled radio button panels

---

src/framework/preferences/css/stylus/PrefsEditor.styl
src/framework/preferences/html/PrefsEditorTemplate-contrast.html
src/framework/preferences/js/Panels.js

https://issues.fluidproject.org/browse/FLUID-6166

FLUID-6166: Fixing class names to use themePicker

---

src/framework/core/js/DataBinding.js
tests/framework-tests/core/js/DataBindingTests.js

See: https://issues.fluidproject.org/browse/FLUID-6158
Documentation pull request: https://github.com/fluid-project/infusion-docs/pull/122

FLUID-6158: Add fluid.modelPairToChanges()

---

src/framework/core/js/Fluid.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

https://issues.fluidproject.org/browse/FLUID-6172
Infusion-Docs PR: https://github.com/fluid-project/infusion-docs/pull/124

FLUID-6172: Adding rounding to decimal to round transformation.

---

demos/prefsFramework/index.html
demos/uiOptions/index.html
examples/framework/preferences/conditionalAdjusters-singlePanel/index.html
examples/framework/preferences/conditionalAdjusters/index.html
examples/framework/preferences/usingGrades/index.html
tests/component-tests/uiOptions/html/UIOptions-test.html
tests/manual-tests/framework/preferences/assortedContent/index.html

https://issues.fluidproject.org/browse/FLUID-6173

FLUID-6173: Removing duplicate IDs

---

src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

https://issues.fluidproject.org/browse/FLUID-6174
Infusion-Docs PR: https://github.com/fluid-project/infusion-docs/pull/125

FLUID-6174: Adding an input option to fluid.transforms.valueMapper

---

demos/textfieldControl/index.html

https://issues.fluidproject.org/browse/FLUID-6184

FLUID-6184: Corrected typos in dependency references

---

src/framework/core/js/DataBinding.js
src/framework/core/js/ModelTransformation.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/ModelTransformationTests.js

@kaspermarkus , would you like to take a look?

FLUID-6194: Avoid relaying DELETEs backwards for transformations which do not have inverses

---

Vagrantfile

Includes Chrome 62 and Firefox57

FLUID-6227 - Upgrade to Fedora 27

---

src/module/includes.json

See [FLUID-6245](https://issues.fluidproject.org/browse/FLUID-6245) for details.
cc: @amb26

FLUID-6245: Added new `MessageResolver.js` file to Node.js includes.

---

.npmignore

https://issues.fluidproject.org/browse/FLUID-6237

FLUID-6237: Adding code coverage artifacts to npmignore

---

src/framework/core/frameworkDependencies.json

https://issues.fluidproject.org/browse/FLUID-6252

FLUID-6252: Added MessageResolver.js to the framework dependencies file

---

CODE_OF_CONDUCT.md

https://issues.fluidproject.org/browse/FLUID-6215

FLUID-6215: Adding Code of Conduct to repository

---

demos/prefsFramework/js/prefsEditorDemo.js
examples/framework/preferences/minimalFootprint/fullPage.html
examples/framework/preferences/shared/js/enactors.js
src/components/uiOptions/js/UIOptions.js
src/framework/preferences/js/ArrowScrolling.js
src/framework/preferences/js/Builder.js
src/framework/preferences/js/Enactors.js
src/framework/preferences/js/FullPreviewPrefsEditor.js
src/framework/preferences/js/LetterSpaceEnactor.js
src/framework/preferences/js/Panels.js
src/framework/preferences/js/PrefsEditor.js
src/framework/preferences/js/SelfVoicingEnactor.js
src/framework/preferences/js/SeparatedPanelPrefsEditor.js
src/framework/preferences/js/UIEnhancer.js
tests/framework-tests/preferences/js/BuilderTests.js
tests/framework-tests/preferences/js/IntegrationTestsCommon.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/preferences/js/PrefsEditorTests.js
tests/framework-tests/preferences/js/SelfVoicingPanelTests.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js
tests/manual-tests/framework/preferences/fullPage/js/prefsEditorFullpage.js

https://issues.fluidproject.org/browse/FLUID-6262

FLUID-6262: Adding missing namespaces to prefs framework.

---

examples/framework/preferences/fullPagePanelStyle/index.html

https://issues.fluidproject.org/browse/FLUID-6263

FLUID-6263: Add the markup needed for the table of contents.

---

Gruntfile.js

https://issues.fluidproject.org/browse/FLUID-6255

FLUID-6255: Add a UIO specific distribution.

---

.buildkite/pipeline.yml

Use tag "name" to enforce same agent for all steps.

INFRA-162 - Enforce same agent between steps

---

demos/orator/index.html

https://issues.fluidproject.org/browse/FLUID-6319

FLUID-6319: Fixing typo in dependency

---

src/components/textToSpeech/js/MockTTS.js

https://issues.fluidproject.org/browse/FLUID-6321
https://issues.gpii.net/browse/GPII-3252

FLUID-6321: correcting typo

---

.buildkite/pipeline.yml

https://issues.fluidproject.org/browse/FLUID-6327

FLUID-6327 - Increase timeouts

---

Gruntfile.js
package.json

See [FLUID-6327](https://issues.fluidproject.org/browse/FLUID-6327) for details.

FLUID-6327: Improve lint time.

---

src/components/orator/css/Orator.css

https://issues.fluidproject.org/browse/FLUID-6348

FLUID-6348: Placing the play button at the top of the stack.

---

tests/lib/qunit/js/qunit.js

See [FLUID-6349](https://issues.fluidproject.org/browse/FLUID-6349) for details.

FLUID-6349: Fix timing info reported on QUnit's `testDone` event.

---

Gruntfile.js
src/lib/thirdPartyDependencies.json
src/thirdPartyDependencies.json

Fixes a small linting issue that was breaking the builds.

FLUID-6240: linting

---

src/components/overviewPanel/css/OverviewPanel.css
src/framework/preferences/css/stylus/SeparatedPanelPrefsEditor.styl
src/framework/preferences/css/stylus/SeparatedPanelPrefsEditorFrame.styl
src/thirdPartyDependencies.json

https://issues.fluidproject.org/browse/FLUID-6356

FLUID-6356: fixing font file references

---

src/components/orator/js/Orator.js

https://issues.fluidproject.org/browse/FLUID-6392
Needed to address https://issues.gpii.net/browse/GPII-3977. A dev release of Infusion has also been generated ( 3.0.0-dev.20190807T173919Z.741f09ead.FLUID-6392 ) for testing.

FLUID-6392: Only calling cancel when disabling.

---

.editorconfig
.npmignore
src/framework/core/css/fluidDebugging.css

This PR adds an initial EditorConfig file as per [FLUID-6401](https://issues.fluidproject.org/browse/FLUID-6401).

FLUID-6401: Add editorconfig

---

src/components/orator/css/Orator.css
src/components/orator/js/Orator.js
tests/component-tests/orator/js/OratorTests-Utils.js
tests/component-tests/orator/js/OratorTests.js
tests/framework-tests/preferences/js/SelfVoicingEnactorTests.js

Fixes the position of the selectionReader play button.
https://issues.fluidproject.org/browse/FLUID-6394

FLUID-6394: Position of play button 

---

src/framework/preferences/js/Panels.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js

https://issues.fluidproject.org/browse/FLUID-6426

FLUID-6426: refactoring to remove modification of options.

---

tests/framework-tests/preferences/js/SyllabificationEnactorTests.js

https://issues.fluidproject.org/browse/FLUID-6429

FLUID-6429: Fixing tests to address combined injected syllabification test not running.

---

src/components/orator/js/Orator.js
tests/component-tests/orator/js/OratorTests.js

https://issues.fluidproject.org/browse/FLUID-6436

FLUID-6436: replaced parentElement with parentNode.

---

tests/component-tests/uiOptions/js/UIOptionsTests.js
tests/framework-tests/preferences/html/LocalizationPrefsEditor-test.html

https://issues.fluidproject.org/browse/FLUID-6451

Fluid 6451: Use temp store and configure ToC in UIO tests.

---

tests/framework-tests/core/js/Keyboard-a11yTests.js

Had to remove the test for `onLeaveContainer` because we are not able 
to synthesize keyboard events for `Tab`.
Note: The `simulateKeyDown` method updated in this PR will likely not work for pre-chromium versions of MS Edge. There are some differences between how IE, pre-chromium MS Edge, and the latest browsers all support the synthesis of key events.
https://issues.fluidproject.org/browse/FLUID-6488

FLUID-6488: Fixed failing keyboard a11y tests.

---

README.md

Removed the VM in "Run Tests In a VM"

typo fix: Removed the VM

---

src/framework/preferences/js/Store.js
tests/framework-tests/preferences/js/StoreTests.js

Updates defaults to set samesite attribute.
https://issues.fluidproject.org/browse/FLUID-6497

FLUID-6497: Can now set any cookie attribute.

---

.dockerignore
.npmignore
Dockerfile
README.md

How to test:
```
$ docker build -t infusion .
$ docker run --rm -ti -p 8000:80 infusion
$ open http://localhost:8000
```

FLUID-6288 Add Dockerfile

---

demos/uiOptions/index.html
src/framework/preferences/css/stylus/utils/Themes.styl

https://issues.fluidproject.org/browse/FLUID-6525

FLUID-6525: Style placeholder text in contrast themes.

---

src/framework/preferences/css/stylus/SeparatedPanelPrefsEditorFrame.styl

https://issues.fluidproject.org/browse/FLUID-6532

FLUID-6532: Center UIO Panel

---

src/components/orator/js/Orator.js
src/components/textToSpeech/js/MockTTS.js
src/components/textToSpeech/js/TextToSpeech.js
tests/component-tests/orator/js/OratorTests.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js

https://issues.fluidproject.org/browse/FLUID-6533

FLUID-6533: Handling errors from SpeechSynthesisUtterance instances.

---

demos/prefsFramework/index.html
src/framework/preferences/css/stylus/Enactors.styl
src/framework/preferences/js/SyllabificationEnactor.js
tests/framework-tests/preferences/js/SyllabificationEnactorTests.js

https://issues.fluidproject.org/browse/FLUID-6554

FLUID-6554: Fix infinite loop of syllabification for &shy;

---

.github/workflows/ci.yml

Rationale: https://issues.fluidproject.org/browse/FLUID-6556

FLUID-6556 Add Node.js 14.x and drop 10.x from the test matrix

---

Gruntfile.js
package.json

See [FLUID-6555](https://issues.fluidproject.org/browse/FLUID-6555) for details.
cc: @amb26

FLUID-6555: Use fluid-grunt-lint-all for linting.

---

Dockerfile

This was an oversight while updating CI to use Node.js 14

FLUID-6556 Update Docker image to Node.js 14

---

demos/prefsFramework/html/SimplifyPanelTemplate.html
demos/switch/index.html
examples/framework/preferences/shared/html/switch-template.html
src/framework/preferences/html/PrefsEditorTemplate-captions.html
src/framework/preferences/html/PrefsEditorTemplate-enhanceInputs.html
src/framework/preferences/html/PrefsEditorTemplate-layout.html
src/framework/preferences/html/PrefsEditorTemplate-speak.html
src/framework/preferences/html/PrefsEditorTemplate-syllabification.html
tests/component-tests/switch/html/Switch-test.html

https://issues.fluidproject.org/browse/FLUID-6565

FLUID-6565: Prevent form submission from clicking switches in prefs editor

---

package.json

NOJIRA: update nyc to match fluid-testem

---

src/components/switch/js/Switch.js

FLUID-6539: remove activateHandler from switch

---

README.md

Updates badge to point to new tests workflow.

NOJIRA: update badge to reference test workflow

---

package.json

https://issues.fluidproject.org/browse/FLUID-6604

FLUID-6604: Update to latest jQuery (v3.6.0)

---

buildModules.js

https://issues.fluidproject.org/browse/FLUID-6618

FLUID-6618: Fix path to source maps for package builds.

---

ReleaseNotes.md

https://issues.fluidproject.org/browse/FLUID-6677

FLUID-6677: add Infusion 3.0 release notes

---

tests/lib/qunit/js/qunit.js

https://issues.fluidproject.org/browse/FLUID-6684

FLUID-6684: address Safari issues by clearing fixture.innerHTML before resetting it.

---

src/framework/preferences/css/sass/SeparatedPanelPrefsEditor.scss

https://issues.fluidproject.org/browse/FLUID-6705

FLUID-6705: prevent line-space from affecting position of sliding panel tab

---

demos/uiOptions/css/uiOptions.css
package.json
src/framework/preferences/js/Enactors.js
tests/framework-tests/preferences/html/Enactors-test.html

https://issues.fluidproject.org/browse/FLUID-6696

FLUID-6696: Ensure that ToC is shown when initialized.

---

CHANGELOG.md
ReleaseNotes.md

https://issues.fluidproject.org/browse/FLUID-6724

FLUID-6724: Updating release notes and change log  for 4.0 release

---

package.json
src/components/inlineEdit/package.json
src/components/orator/package.json
src/components/overviewPanel/package.json
src/components/pager/package.json
src/components/progress/package.json
src/components/reorderer/package.json
src/components/slidingPanel/package.json
src/components/switch/package.json
src/components/tableOfContents/package.json
src/components/textToSpeech/package.json
src/components/textfieldControl/package.json
src/components/tooltip/package.json
src/components/uiOptions/package.json
src/components/undo/package.json
src/components/uploader/package.json
src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
src/framework/core/package.json
src/framework/enhancement/package.json
src/framework/preferences/package.json
src/framework/renderer/package.json
tests/framework-tests/core/js/DataBindingTests.js

https://issues.fluidproject.org/browse/FLUID-6728 - sourcePath of Number 0 doe not get interpolated
https://issues.fluidproject.org/browse/FLUID-6729 - sourcePath cannot be injected into model
Preparing for 4.1.0 Infusion release

FLUID-6728, FLUID-6729: Cases from ADTKINS involving sourcePath

---

tests/framework-tests/core/js/FluidIoCTests.js

Test case for:
https://issues.fluidproject.org/browse/FLUID-6735

FLUID-6735: Test case for issue

---

src/framework/preferences/js/SeparatedPanelPrefsEditor.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorResponsiveTests.js

To resolve [FLUI-6748](https://issues.fluidproject.org/browse/FLUID-6748).

FLUID-6748: remove the auto save of panel index in separated panel UIO

---

src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js

https://issues.fluidproject.org/browse/FLUID-6756

FLUID-6756: move global framework functions to fluid namespace

---

src/components/orator/js/Orator.js
src/components/textToSpeech/js/TextToSpeech.js

Fixes TTS read back of selected text in Firefox.
Allows rendering and other functions to be overridden via invokers and listener namespaces.
https://issues.fluidproject.org/browse/FLUID-6757
https://issues.fluidproject.org/browse/FLUID-6758

FLUID-6758, FLUID-6757: TTS function overriding and playback

---

CHANGELOG.md
ReleaseNotes.md
package.json
src/framework/core/js/Fluid.js

https://issues.fluidproject.org/browse/FLUID-6759

FLUID-6759: update change log for 4.6 release
