demos/inlineEdit/json/config.json
demos/pager/json/config.json
demos/prefsFramework/json/config.json
demos/progress/json/config.json
demos/renderer/json/config.json
demos/reorderer/gridReorderer/json/config.json
demos/reorderer/imageReorderer/json/config.json
demos/reorderer/layoutReorderer/json/config.json
demos/reorderer/listReorderer/json/config.json
demos/tableOfContents/json/config.json
demos/uiOptions/json/config.json
demos/uploader/json/config.json

Note that
a) we have nothing at all in the docs yet for the Keyboard a11y plugin
b) we have nothing in the docs yet about browser support
so those two links are still referencing the archived docs wiki

FLUID-5625: Update demo APIl links to new production docs url

---

demos/prefsFramework/index.html
demos/prefsFramework/js/prefsEditorDemo.js
demos/tableOfContents/index.html
demos/tableOfContents/js/tableOfContentsDemo.js
demos/uiOptions/index.html
src/components/tableOfContents/js/TableOfContents.js
src/components/uiOptions/js/UIOptions.js
src/framework/preferences/js/Enactors.js
tests/component-tests/tableOfContents/html/TableOfContents-test.html
tests/component-tests/tableOfContents/js/TableOfContentsTests.js

Added a class that can be used to exclude a header or section of headers from being included in the Table of Contents.
https://issues.fluidproject.org/browse/FLUID-5697

FLUID-5697: provide a means of excluding headers

---

.npmignore

This applies @jobara's FLUID-5458 changes to .npmignore to the 1.9.x branch. @jobara or @amb26, can you have a look and merge if it looks good? This should match the version in the new 2.0-era master.

FLUID-5458: Updates .npmignore for 1.9.x branch.

---

demos/prefsFramework/js/prefsEditorDemo.js
src/components/inlineEdit/js/InlineEdit.js
src/components/pager/js/Pager.js
src/components/tableOfContents/js/TableOfContents.js
src/framework/core/js/Fluid.js
src/framework/core/js/FluidView.js
src/framework/core/js/jquery.standalone.js
src/framework/preferences/js/AuxBuilder.js
src/framework/preferences/js/Builder.js
src/framework/preferences/js/Enactors.js
src/framework/preferences/js/Panels.js
src/framework/preferences/js/PrefsEditor.js
src/framework/preferences/js/SelfVoicingEnactor.js
tests/component-tests/pager/html/PagedTable-test.html
tests/component-tests/pager/js/PagedTableTests.js
tests/component-tests/uploader/js/ErrorPanelTests.js
tests/framework-tests/core/js/FluidIoCTests.js
tests/framework-tests/enhancement/js/ContextAwarenessTests.js
tests/framework-tests/preferences/js/AuxBuilderTests.js
tests/framework-tests/preferences/js/BuilderTests.js
tests/framework-tests/preferences/js/PanelTestUtils.js
tests/framework-tests/preferences/js/PrefsEditorTests.js
tests/test-core/jqUnit/js/jqUnit.js

overriding order is now left to right. Also eliminated $.inArray from our jQuery standalone, in favour of plain Array.indexOf in environments where only an array is expected (or fluid.contains which has always worked). Corrected comments for assertLeftHand/assertRightHand which exhibit a similar lack of ability to distinguish things which either are larger or smaller than another thing or lie to the left or right of it.
@colinbdclark  - one for you

FLUID-5743: Removed ARABIC GRADES from the framework - 

---

src/framework/core/js/Fluid.js
tests/framework-tests/core/js/FluidIoCTests.js

of mergeOneImpl - this logic all needs revisiting for FLUID-4982
Thanks for the report and test case, @colinbdclark

FLUID-5755: Fix to failed detection of non-plain objects in 2nd branch

---

src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
tests/framework-tests/core/all-tests.html
tests/framework-tests/core/html/FluidIoC-test.html
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidIoCTests.js

The configuration at least no longer throws on registration, even if merged result is still incorrect. However, the removal of the cognitively lost "mergeModel" and other cruft from the mergeOneImpl loop is highly worthwhile since this loop is very hot as well as poorly understood. Also able to remove fluid.isDOMish since the new fluid.isPlainObject is powerful enough to reject markers as well as anything DOMlike even in IE9 (which is itself 1 revision below our minimum support).
These were never entered into our documentation as inherently suspicious.

FLUID-5800: Basics for fixing "baseless merge" issues

---

src/framework/preferences/js/AuxBuilder.js
tests/framework-tests/preferences/js/AuxBuilderTests.js

When more than one panel names defined in the aux schema use single letters, and these panels compose a composite panel using the expression of "panels: ["x", "y", ...], the builder mistakenly sets the renderOnPrefs option to true for some panels even though all panels should always be rendered.
@jobara, can you review this pull request? Thanks.

FLUID-5759: A bug fix for the auxiliary schema builder

---

.gitignore
Gruntfile.js
README.md
Vagrantfile
package.json
provisioning/playbook.yml
provisioning/requirements.yml
provisioning/vars.yml
tests/all-tests.html
tests/testem.json

These changes let anyone launch installed browsers and have them run Infusion tests and also run the tests in a Fedora VM. Test results are displayed in the host operating system's console in both cases.

GPII 1550: Adds changes required for automated tests

---

src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

* Now uses fluid.model.isSameValue form comparison instead of === and !==
* the logical or (||) operator now always returns either true or false as opposed to returning the first value in case of false (which javascript does).
* Unit tests for new features

FLUID-2845, FLUID-5669: Improved the binaryOp model transformation

---

tests/framework-tests/preferences/html/SelfVoicingEnactor-test.html
tests/framework-tests/preferences/js/SelfVoicingEnactorTests.js

The test markup had been inside a qunit-fixture; however, qunit was clearing out
the markup causing the test component to initialize without all of the markup it
was expecting. This was only an issue in IE. I've removed the fixture as there
is only one test that uses the markup.
https://issues.fluidproject.org/browse/FLUID-5730

FLUID-5730: removed qunit-fixture element

---

demos/prefsFramework/index.html
src/components/slidingPanel/js/SlidingPanel.js
src/framework/preferences/html/PrefsEditorTemplate-lineSpace.html
src/framework/preferences/html/PrefsEditorTemplate-textSize.html
src/framework/preferences/js/SeparatedPanelPrefsEditor.js
src/framework/preferences/messages/prefsEditor.json
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js

* aria-labels for icons removed with the addition of `display = "presentation"`
* aria-labels added for show/hide button
This pull request should be merged **after** [FLUID-5682](https://github.com/fluid-project/infusion/pull/619)

Fluid 5680: Hide icons from AT and added aria-label for hide/show button

---

Gruntfile.js
src/components/pager/js/PagedTable.js
src/components/pager/js/Pager.js
src/components/pager/js/Table.js
src/components/slidingPanel/js/SlidingPanel.js
src/components/tableOfContents/js/TableOfContents.js
src/components/uploader/js/UploaderCompatibility-Infusion1.2.js
src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
src/framework/core/js/FluidIoC.js
src/framework/core/js/ModelTransformation.js
src/framework/core/js/ModelTransformationTransforms.js
src/framework/enhancement/js/ContextAwareness.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidIoCTests.js
tests/framework-tests/core/js/FluidJSTests.js
tests/framework-tests/core/js/ModelTransformationTests.js
tests/framework-tests/preferences/js/BuilderTests.js
tests/framework-tests/preferences/js/EnactorsTests.js
tests/framework-tests/preferences/js/IntegrationTestsCommon.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/preferences/js/PrefsEditorTests.js
tests/framework-tests/renderer/js/RendererUtilitiesTests.js
tests/test-core/utils/js/IoCTestUtils.js

FLUID-5695: Allow "invalidation-style" model listeners to listen to multiple paths
FLUID-5848: Detect indirect references to model components from model listeners and relay rules

FLUID-5695, etc.: Numerous improvements to ChangeApplier and model transforms

---

src/components/progress/js/Progress.js
tests/component-tests/progress/js/ProgressTests.js

Fixes FLUID-3797
1. Removed callback with appropriate event.
2. Fixed tests for the same.
Test -
Progress-test is running successfully for the made changes.

FLUID-3797: Remove deprecated callbacks from progress component

---

tests/framework-tests/core/js/CachingTests.js
tests/framework-tests/core/js/FluidViewTests.js

Update asynchronous unit tests to use asyncTest instead of stop() in
CachingTests.js and FluidViewTests.js
Test-
Tested by running the test.

FLUID-4137: Update asynchronous unit tests

---

demos/reorderer/imageReorderer/index.html

FLUID-3258: Extra < div> in Image Reorderer demo markup not necessary.
The extra < div> tag removed.

FLUID-3258: Extra <div> in Image Reorderer demo markup not necessary

---

src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidJSTests.js
tests/test-core/utils/js/IoCTestUtils.js

at a single applier. This rebalances the implementation of change events and standard events, with the former now implemented in terms of the latter. This introduces a new options-based API for event.addListener and an improved fluid.isPlainObject.

FLUID-5886: Fix for failure to deduplicate model listeners by namespace

---

src/framework/core/js/DataBinding.js
src/framework/core/js/Fluid.js
src/framework/core/js/ModelTransformation.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

* Rolled the switcheroo of inputPath and outputPath for standardTransformFunctions into the general framework inversion functions.
* Went through all transforms and checked for correctness and tests.
* Notes on invertibility will be added to the documentation (currently kept here: https://issues.fluidproject.org/browse/FLUID-5133) - will be added after discussion with antranig
* Added inRange and quantize functions (FLUID-5890)
* Added inverse function of stringToNumber (namely numberToString) - plus made both functions lenses
* Changed arrayToSetMembership and setMembershipToArray's grades to be standardTransformFunction
* Added a few tests where needed

FLUID-5133/FLUID-5890/FLUID-5478: Improved support for inversion.

---

Vagrantfile
provisioning/vars.yml

Spinning up a vagrant box was failing for me. I'm assuming it's related to someone upstream removing the recipe for Node.js 0.10.40 since it's so old. This pull request updates us to the latest LTS version of Node.js, as well as to Fedora 23.

Updates Fedora to 23 and Node.js to the LTS branch.

---

.eslintrc.json
tests/framework-tests/preferences/html/SelfVoicingPanel-test.html
tests/lib/qunit/js/qunit.js
tests/test-core/utils/js/IoCTestUtils.js

QUnit patched to support new "testsArriving" config member, which is now used by IoC Testing Framework

FLUID-5810: Fix for erratic failure of tests. 

---

src/framework/preferences/js/Panels.js
src/framework/preferences/messages/lineSpace.json
src/framework/preferences/messages/textSize.json
tests/framework-tests/preferences/data/lineSpace_en.json
tests/framework-tests/preferences/data/textSize_en.json
tests/framework-tests/preferences/js/PanelsTests.js

It was determined in FLUID-5680 that the icons for the sliders are presentational.
The labels were not being used either so I have removed all of the strings and associated
code to insert them into the DOM.
https://issues.fluidproject.org/browse/FLUID-5192

FLUID-5192: Removed strings for slider icons

---

tests/component-tests/tooltip/html/Tooltip-test.html
tests/component-tests/tooltip/js/TooltipTests.js

When the iframe source was set in the document, it could load before the load event is bound.
This prevented the test from working as it was waiting for the load event.
https://issues.fluidproject.org/browse/FLUID-5872

FLUID-5872: Setting the iframe source programmatically

---

src/framework/preferences/js/Enactors.js
src/framework/preferences/js/FullNoPreviewPrefsEditor.js
src/framework/preferences/js/FullPreviewPrefsEditor.js
src/framework/preferences/js/Panels.js
src/framework/preferences/js/SeparatedPanelPrefsEditor.js

Added namespaces to the listeners in the prefs framework. The exception is when listeners are bound to events of other components using IoC. These have not be namespace due to [FLUID-5948](https://issues.fluidproject.org/browse/FLUID-5948)
https://issues.fluidproject.org/browse/FLUID-5209

FLUID-5209: Adding namespaces to listeners in the Prefs Framework

---

package.json
src/module/fluid.js

This pull request replaces #735 - in addition to the check made there, we also need to fix an underlying issue in the "resolve" module - see https://github.com/substack/node-resolve/issues/106 for details.
I've run the following test - firstly, the reproduction steps listed on #735 of checking out, for example, kettle in "C:\kettle", running npm install, and then npm test from the kettle directory itself. Also, I have run   https://github.com/GPII/universal with its infusion patched in-place to this version to check it starts up ok. Perhaps you can think of other tests. In general this issue is ludicrously hard to test because of its large number of environmental assumptions and dependencies, down to the use of a particular shell on Windows.

FLUID-5940: Correct problems with auto-deduping Infusion on Windows

---

.gitignore
Gruntfile.js
tests/testem.json

These changes make Testem generate a TAP report that can be used by Jenkins.

FLUID-5917: Makes Testem generate a TAP report

---

src/components/textToSpeech/js/TextToSpeech.js

This small patch addresses the two issues documented in https://issues.fluidproject.org/browse/FLUID-5951
This means the tests run (and all pass) in the latest MS Edge, which [recently added TTS support](https://blogs.windows.com/msedgedev/2016/06/01/introducing-speech-synthesis-api)

FLUID-5951: update checkTTSSupport to work in MS Edge

---

src/components/inlineEdit/js/InlineEdit.js
src/components/tooltip/js/Tooltip.js

From the jQuery height docs (http://api.jquery.com/height/)
"As of jQuery 1.8, this may require retrieving the CSS height plus box-sizing property and then subtracting any potential border and padding on each element when the element has box-sizing: border-box. To avoid this penalty, use .css( "height" ) rather than .height()."
https://issues.fluidproject.org/browse/FLUID-5980

FLUID-5980: Adjusting the height calculation.

---

src/framework/enhancement/js/ContextAwareness.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js
tests/test-core/utils/js/ConditionalTestUtils.js

This fixes the bug introduced by FLUID-5973 when running Infusion in non-browser contexts, as mentioned by @amb26 at https://github.com/fluid-project/infusion/pull/577#issuecomment-255065212 & encountered by @the-t-in-rtf 
The `fluid.contextAware.getBrowserPlatformName` function now makes sure a `navigator` object actually exists before attempting to access any properties.
I've also updated various variable and function names to make it clear this functionality only currently extends to the OS platform as reported in the browser context.
Confirmed both the in-browser tests and `basic-node-tests.js` are now passing.

FLUID-5985: Fix trunk-breaking bug introduced by FLUID-5973 in non-browser contexts

---

tests/node-tests/README.md
tests/node-tests/basic-node-tests.js
tests/node-tests/tap-reporting.js
tests/testem.json

* Modifies the `testem.json` configuration to add a custom "Node Module Basic Packaging Tests" launcher to run `basic-node-tests.js` as part of the overall test run
* Modifies `basic-node-tests.js` to accept a command-line flag of `--tap`; if supplied, it will output a TAP-format report (see https://github.com/testem/testem#processes-with-tap-output) that can be consumed and reported by Testem
* Modifies `basic-node-tests.js` to exit with a non-zero exit code if any tests fail, to better support usage in CI
The node packaging tests will now be run as part of the `grunt tests` tasks in the VM, or locally with `testem ci --file tests/testem.json`
You can run the node packaging tests as part of Testem separately with this command: `testem ci --file tests/testem.json --launch "Node Module …

FLUID-5986: Integration of basic-node-tests.js with Testem runner

---

demos/inlineEdit/index.html
demos/overviewPanel/index.html
demos/prefsFramework/index.html
demos/renderer/index.html
demos/reorderer/listReorderer/index.html

This fixes a number of small (but validator-breaking) markup issues in the demo index pages.
It should be noted there may be some issues as well in markup injected by demo components, such as https://issues.fluidproject.org/browse/FLUID-5994 - these should be tackled separately, since they may be more complex.
Tagging @jobara

FLUID-6000: Make sure all Infusion core demo index pages pass markup validation 

---

demos/inlineEdit/json/config.json
demos/keyboard-a11y/js/keyboardDemo.js
demos/keyboard-a11y/json/config.json
demos/overviewPanel/index.html
demos/pager/json/config.json
demos/prefsFramework/json/config.json
demos/progress/json/config.json
demos/renderer/json/config.json
demos/reorderer/gridReorderer/json/config.json
demos/reorderer/imageReorderer/json/config.json
demos/reorderer/layoutReorderer/json/config.json
demos/reorderer/listReorderer/json/config.json
demos/tableOfContents/json/config.json
demos/uiOptions/json/config.json
demos/uploader/json/config.json

This turned out to be a fairly simple fix related to updating the `aria-role` attributes and space-encoding the mailto URL.
JIRA reporting it https://issues.fluidproject.org/browse/FLUID-5994
Tagging @jobara 
I'm fixing a few of the other issues with the injected markup under this heading as well, such as space-encoding all the `mailto` URLs.

FLUID-5994: fix HTML validator issues in keyboard A11Y demo components

---

src/components/tableOfContents/js/TableOfContents.js
tests/component-tests/tableOfContents/js/TableOfContentsTests.js

The ToC now points at the ID of a header item instead of creating an empty anchor to point at. 
https://issues.fluidproject.org/browse/FLUID-6011

FLUID-6011: Using IDs instead of empty links for ToC

---

src/components/uploader/js/FileQueueView.js

The aria-label had include the remove information that was only relevant before
the file was uploaded. This has been removed. The state of the file row is still
updated in the title attribute, which contains the removal instructions before uploading
and says "file uploaded" after.
https://issues.fluidproject.org/browse/FLUID-6025

FLUID-6025: Removing delete instructions from the row labels

---

src/components/uploader/html/Uploader.html

Switched from fl-uploader-hidden to fl-hidden-accessible so that the label of the
button would not be removed from the accessibility tree
https://issues.fluidproject.org/browse/FLUID-6027

FLUID-6027: Switching to fl-hidden-accessible from fl-uploader-hidden

---

Gruntfile.js
README.md
package.json
src/framework/preferences/css/stylus/PrefsEditor.styl
src/framework/preferences/css/stylus/utils/Helpers.styl
src/framework/preferences/css/stylus/utils/Themes.styl

This addresses both https://issues.fluidproject.org/browse/FLUID-6017 and https://issues.fluidproject.org/browse/FLUID-6018 by styling the native sliders with CSS, using the techniques described at https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/
Additionally, since it's rather painful to run `grunt buildStylus` each time when doing Stylus development, I've added a `grunt watch:buildStylus` task using `grunt-contrib-watch` that automatically recompiles Stylus -> CSS as changes are made. I ended up doing this as a local customization at first and then concluded it might be generally useful for the project.
Needs to be tested with IE and Edge, will do so when in the office later this morning. Opening PR now for review of the basic approach.
Tagging @jobara

FLUID-6017 + FLUID-6018: style native HTML sliders with CSS, make them responsive to prefs framework enactors

---

demos/progress/js/progressDemo.js
src/components/progress/js/Progress.js
tests/component-tests/progress/js/ProgressTests.js

- Added the progress label text update back to the demo
- Updated the progress component to optionally interpolate the percentage into a string template
https://issues.fluidproject.org/browse/FLUID-6032

FLUID-6032: Fixing progress label

---

src/components/uploader/js/HTML5UploaderSupport.js

In IE and Edge the "Enter" keydown event is translated to a click event to trigger the opening of the file open dialog. This is to prevent it from automatically triggering a form submission instead.
https://issues.fluidproject.org/browse/FLUID-6056

FLUID-6056: Handle the "enter" key to open the file dialog

---

src/components/pager/js/Pager.js
src/components/uploader/js/FileQueueView.js
src/components/uploader/js/Uploader.js
tests/component-tests/uploader/js/FileQueueViewTests.js

Removes `role="application"` from pager and moves it to the file queue in Uploader.
This PR continues on from work started in https://github.com/fluid-project/infusion/pull/786
https://issues.fluidproject.org/browse/FLUID-6064

FLUID-6064: 

---

Gruntfile.js

The verbose setting now only affects stderr, as the stdout needs to be returned by the function
https://issues.fluidproject.org/browse/FLUID-6086

FLUID-6086: Fixing stdio option to allow stdout

---

tests/manual-tests/components/inlineEdit/rich/index.html

Rectify spelling error of the word "itself" from "itslef" in the description section of rich inline edit page.

FLUID-6029: Rectify spelling error of the word "itself" 

---

src/framework/enhancement/js/ContextAwareness.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js
tests/test-core/utils/js/ConditionalTestUtils.js

This issue is described at https://issues.fluidproject.org/browse/FLUID-6103, and a bug has been filed with (and acknowledged by) the Chromium team around the non-firing of the `textToSpeech.onpause` and `textToSpeech.onresume` events in the current version of Chrome on Windows: https://bugs.chromium.org/p/chromium/issues/detail?id=679043
Making PR for review purposes and discussion of how to best address the immediate issue (a browser bug in Chrome is causing test failure).

FLUID-6103: address Chrome-on-Windows pause/resume failures introduced by Chrome regression

---

src/framework/preferences/css/stylus/PrefsEditor.styl
src/framework/preferences/css/stylus/SeparatedPanelPrefsEditorFrame.styl
src/framework/preferences/messages/contrast.json

This is an interim solution, as the arrows are not interactive and can not
be used to scroll the panels. Rather in this implementation they are just
used to indicate that there is additional content that can be manually scrolled to.
https://issues.fluidproject.org/browse/FLUID-5534
NOTE: There is a bug in IE 11 where the headers between panels do not line up. ( see: [FLUID-6154](https://issues.fluidproject.org/browse/FLUID-6154) )

FLUID-5534: Adding arrows to indicate additional content

---

src/framework/preferences/js/Panels.js
tests/framework-tests/preferences/js/PanelsTests.js

The textFont and contrast panels will replace the arrays that are used
to control their rendering.
https://issues.fluidproject.org/browse/FLUID-6165

FLUID-6165: Adding a replace merge policy for controlValues

---

src/framework/preferences/js/Store.js
tests/framework-tests/preferences/html/Store-test.html
tests/framework-tests/preferences/js/PageEnhancerTests.js
tests/framework-tests/preferences/js/StoreTests.js

All stores now derive fluid.prefs.dataSource. fluid.prefs.store defaults
to use the cookie store but can use other stores based on context.
https://issues.fluidproject.org/browse/FLUID-6169

FLUID-6169: removed fluid.prefs.store as grade for temp and cookie store

---

src/framework/preferences/js/Panels.js
src/framework/renderer/js/RendererUtilities.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/renderer/html/RendererUtilities-test.html
tests/framework-tests/renderer/js/RendererUtilitiesTests.js

The renderer expander will now also resolve IoC references for the
selectID. rowID, labelID, and inputID all point at values in the
selectors block and do not resolve IoC references.
https://issues.fluidproject.org/browse/FLUID-6171

FLUID-6171: adding IoC resoltion to fluid.renderer.selection.inputs

---

src/module/fluid.js
tests/node-tests/README.md
tests/node-tests/basic-node-tests.js
tests/node-tests/tap-reporting.js

Also fix for FLUID-5920 to ensure that default global uncaught exception handler causes system exit with failure. General tidying and reorganisation of basic node tests and their entanglement with TAP reporting

FLUID-6188: Make sure that fluid.loadTestingSupport is idempotent.

---

src/framework/preferences/js/SeparatedPanelPrefsEditor.js

MS Edge cuts off the bottom of the adjusters so the height needed to be recalculated in order to show the entire UIO panel.

FLUID-6183: Added height variable to recalculate panel height.

---

src/framework/core/js/Fluid.js
src/framework/preferences/js/ArrowScrolling.js
tests/framework-tests/core/js/FluidJSTests.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorResponsiveTests.js

Whether scrolling with the keyboard (arrow keys, tabs), mouse, or clicking on the arrow buttons the last viewed adjuster should persist after closing and reopening the panel ( even on page reload if a cookie or other similar long term storage is used ).
https://issues.fluidproject.org/browse/FLUID-6180
This includes changes from https://github.com/fluid-project/infusion/pull/844

FLUID-6180: Adding persistence for adjuster selection in responsive display

---

src/framework/preferences/css/stylus/PrefsEditor.styl

This is to keep it hidden, but also allow it scroll into view when tab
focused.
https://issues.fluidproject.org/browse/FLUID-6228
*NOTE: For Firefox and IE 11 when tab focusing to the element, it will only show the smallest amount necessary. The other browsers do a better job of scrolling the entire widget into view.*

FLUID-6228: Positioning radio button behind label.

---

.buildkite/pipeline.yml
.npmignore

The block step has been added to the Infusion pipeline using the Buildkite web UI. This ensures it can't be removed by accident in a PR.

NOJIRA: Removes block step

---

src/components/reorderer/js/Reorderer.js

Removed the Stylistic Offset selectable; Tested on Google Chrome 64, Firefox 58 on Windows 10; did not cause any issues to the Reorderer demo.
Please Review :)

FLUID-4016: Investigate and possibly remove "stylisticOffset" from reorderer options

---

.buildkite/pipeline.yml

These timeouts take into account how long Infusion CI jobs currently take. They should avoid scenarios like the one experienced today where [stalled tests prevented other jobs from running](https://buildkite.com/fluid-project/fluid-infusion/builds/121).

NOJIRA: Adds more timeouts to CI stages

---

Vagrantfile

Use the "debug" callback plugin instead of the default. Despite its name, the output should be easier.
Example of hard to read output: https://buildkite.com/fluid-project/fluid-infusion/builds/166#52fa9dbc-db86-4f10-8191-ebabf5a3b522/18-235
Example of easy to ready output (notice the failed task preserves the command's output):
```
default: TASK [nodejs : Clone application repository] ***********************************
default: skipping: [localhost]
default: 
default: TASK [nodejs : Make sure the application install directory exists and is owned by the appropriate user] ***
default: ok: [localhost]
default: 
default: TASK [nodejs : Run application related commands as the application user] *******
default: failed: [localhost] (item=npm install) => {
default:     "changed": true, 
default: …
```

FLUID-6269 - Make Ansible error output more readable

---

.buildkite/pipeline.yml

The VM provisioning phase already installs dependencies and builds infusion, so this PR removes those steps from the CI configuration.
Additionally, I'm proposing to rename the jobs:
* Create VM -> Build
* Run tests -> Test
* Destroy VM -> Cleanup
* Browser and node tests are separate steps
* Added code linter step
* Made last step (Cleanup) run even if previous steps failed (so the VM gets destroyed)

FLUID-6266 - Remove extra CI steps, add linting and rename stages

---

src/framework/preferences/js/Enactors.js
tests/framework-tests/preferences/html/Enactors-test.html
tests/framework-tests/preferences/js/EnactorsTests.js

When a browser returns "normal" as the initial line-height, the enactor will set the line-height back to "normal" when no line-height multiplier needs to be set. That is, when there are no preferences for line-height to apply.
https://issues.fluidproject.org/browse/FLUID-6279

FLUID-6279: improving handling of "normal" initial line-height.

---

.buildkite/pipeline.yml

Right now, Buildkite will distribute builds to any agent that is only.
This definition is needed to it targets agents that can properly run the Vagrant-based steps.
Since it's still not possible to define the agent at the pipeline level, each step must define the tags independently. To keep it DRY, it uses YAML anchors.

INFRA-162 - Specify tags to target h-0005

---

src/framework/core/js/FluidDebugging.js
src/framework/core/js/ModelTransformation.js
src/framework/core/js/ModelTransformationTransforms.js

https://issues.fluidproject.org/browse/FLUID-6314

FLUID-6314: Fixing versioned infusion namespace.

---

package.json
provisioning/vars.yml

This effectively ensures that "grunt BuildDist && grunt BuildStylus" only run during "npm publish" and not at "npm install" time.

FLUID-6309 - Use npm prepublishOnly instead of prepublish

---

Vagrantfile

In certain situations, it's perfectly fine to have the node_modules shared between host and a vagrant box:
* When host/VM architecture are the same
* When all work happens inside the VM
That is the situation in CI Linux build nodes.
This has the advantage that certain operations like publishing the build artifacts can happen outside the VM (as they need access to credentials that would be hard to import into the VM) without having to run `npm install` a second time.
This PR adds an environment variable that allow CI (and Linux users) to avoid the bind mount during the `vagrant up` phase by specifying SKIP_NODE_MODULES_BIND_MOUNT=1.

Add SKIP_NODE_MODULES_BIND_MOUNT env var to Vagrantfile

---

Gruntfile.js
package.json
provisioning/vars.yml

This should prevent it from trying to run buildStylus when installed as 
a dependency of another package.
Should also using Infusion as a dependency in another project using 3.0.0-dev.20180913T134630Z.1dc9abaf4.FLUID-6338
https://issues.fluidproject.org/browse/FLUID-6338

FLUID-6338: Moving buildStylus from postInstall to prepare.

---

src/components/orator/css/Orator.css
src/components/orator/js/Orator.js
src/framework/preferences/css/stylus/utils/Themes.styl
tests/component-tests/orator/js/OratorTests-Utils.js
tests/component-tests/orator/js/OratorTests.js
tests/framework-tests/preferences/js/SelfVoicingEnactorTests.js

https://issues.fluidproject.org/browse/FLUID-6318

FLUID-6318: Updating the selection reader control to play and stop.

---

src/components/slidingPanel/js/SlidingPanel.js
tests/component-tests/slidingPanel/js/SlidingPanelTests.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorResponsiveTests.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js

This is to conform with the aria spec. See: 
https://www.w3.org/WAI/GL/wiki/Using_aria-expanded_to_indicate_the_state_of_a_collapsible_element
https://issues.fluidproject.org/browse/FLUID-6357

FLUID-6357: Moving aria-expanded to the button instead of the panel.

---

src/components/orator/js/Orator.js
tests/component-tests/orator/js/OratorTests.js

Taking into consideration margin of container when positioning TTS selection reader control.
https://issues.fluidproject.org/browse/FLUID-6394
dev release for testing: 3.0.0-dev.20190820T145526Z.389bd6937.FLUID-6394
Needed for https://issues.gpii.net/browse/GPII-3767

FLUID-6394: Addressing positioning of TTS selection reader control 

---

examples/framework/preferences/shared/js/primarySchema.js
src/framework/preferences/js/LetterSpacePanel.js
src/framework/preferences/js/LetterSpaceSchemas.js
src/framework/preferences/js/LocalizationPanel.js
src/framework/preferences/js/LocalizationSchemas.js
src/framework/preferences/js/Panels.js
src/framework/preferences/js/StarterGrades.js
src/framework/preferences/js/StarterSchemas.js
src/framework/preferences/js/WordSpacePanel.js
src/framework/preferences/js/WordSpaceSchemas.js
tests/framework-tests/core/js/FluidJSTests.js
tests/framework-tests/preferences/js/AuxBuilderTests.js
tests/framework-tests/preferences/js/LocalizationPanelTests.js
tests/framework-tests/preferences/js/PanelsTests.js
tests/framework-tests/preferences/js/PrimaryBuilderTests.js

First steps for Prefs Framework refactoring. Updating the primary schema entries to use `multipleOf` instead of `divisibleBy` and to have a property for `enumLabels`.
https://issues.fluidproject.org/browse/FLUID-6400

FLUDI-6400: Prefs Framework primary schema updates

---

demos/orator/index.html
demos/prefsFramework/index.html
src/components/orator/css/Orator.css
src/components/orator/js/Orator.js
src/components/textToSpeech/js/MockTTS.js
src/components/textToSpeech/js/TextToSpeech.js
src/framework/core/js/TextNodeParser.js
src/framework/preferences/js/SyllabificationEnactor.js
tests/component-tests/orator/html/Orator-test.html
tests/component-tests/orator/js/OratorTests-Utils.js
tests/component-tests/orator/js/OratorTests.js
tests/component-tests/textToSpeech/js/TextToSpeechTests.js
tests/framework-tests/core/js/TextNodeParserTests.js
tests/framework-tests/preferences/html/CaptionsEnactor-test.html
tests/framework-tests/preferences/html/LetterSpaceEnactor-test.html
tests/framework-tests/preferences/html/LocalizationEnactor-test.html
tests/framework-tests/preferences/html/WordSpaceEnactor-test.html

When reading through text, if the a language code is supplied it will be passed to the web speech api. This includes both reading through the page or a reading a selection.
https://issues.fluidproject.org/browse/FLUID-6278
dev release for testing: 3.0.0-dev.20191007T194251Z.4ef5356a5.FLUID-6278
Note: that there may be issues with MS Edge if the synthesizer for the particular language is not available.

FLUID-6278: Passes along the lang code for each block of text being synthesized

---

src/components/orator/js/Orator.js
src/framework/core/js/TextNodeParser.js
src/framework/preferences/js/SyllabificationEnactor.js
tests/framework-tests/core/html/TextNodeParser-test.html
tests/framework-tests/core/js/TextNodeParserTests.js

- combined with fluid.textNodeParser.hasVisibleText
- improvements to algorithm for ignoring non-rendered text
Dev release to test with UIO+: 3.0.0-dev.20191104T213827Z.4f3dd87a8.FLUID-6422-UIO-Plus-Build (has merged FLUID-6148 branch)
https://issues.fluidproject.org/browse/FLUID-6422

FLUID-6422: Refactoring fluid.textNodeParser.hasTextToRead

---

src/components/orator/js/Orator.js
tests/component-tests/orator/js/OratorTests-Utils.js
tests/component-tests/orator/js/OratorTests.js
tests/framework-tests/preferences/js/SelfVoicingEnactorTests.js

Right Clicks in some browsers also perform a selection. In Safari and 
Chrome those selectionchange events fire twice but with the same text 
selection so there is no time where the UI would have been removed. By 
rendering the text on all selection changes, the UI is always at the 
beginning of the text and will follow right click selections.
https://issues.fluidproject.org/browse/FLUID-6431

FLUID-6431: Updating selection button rendering on text change.

---

Vagrantfile

We're currently using Fedora 28 which went [End-Of-Life](https://fedoraproject.org/wiki/End_of_life) (EOL) on 2019-05-28. It also means we're testing with Firefox 66 which was released in March 2019.

FLUID-6486: vagrant: Use Fedora 31 box

---

src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/js/ModelTransformationTests.js

This pull request improves the `arrayToSetMembership` and `setMembershipToArray` transformations by removing the 3rd argument `transformer` and making the 2nd argument `transformSpec` optional. It also includes a detailed description in the form of JSDoc comments and a set of test cases for both the transformations.

FLUID-6500: Improve usability of arrayToSetMembership and setMembershipToArray transforms

---

src/components/orator/js/Orator.js

This will prevent the button from defaulting to "submit" and triggering 
a form submission when pressed.
https://issues.fluidproject.org/browse/FLUID-6512

FLUID-6512: Set the button type.

---

src/framework/preferences/css/stylus/utils/Themes.styl

The textFieldStepper adds focus to a parent element using a class name 
added via JavaScript. Because of the special nature, the focus styling 
needed to be explicitly added for the contrast themes.
https://issues.fluidproject.org/browse/FLUID-6518

FLUID-6518: Add missing styles for textFieldStepper focus.

---

tests/testem.js

Instead of specifying a growing number of browsers that we do not want to run tests on, specify the list of browsers we actually care about.

FLUID-6520 Specify browsers to run tests on

---

.github/workflows/ci.yml

Somehow this was missed in the PR to add Win/macOS tests.
It already exists in the [Kettle](https://github.com/fluid-project/kettle/blob/master/.github/workflows/ci.yml#L23-L24) repo and works fine.

FLUID-6519 ci: Disable git autocrlf

---

.github/workflows/ci.yml

Sometimes CI jobs will hang for a while and the default timeout in GitHub Actions is 360 minutes. This consumes the total of 2000-3000 minutes/month assigned to our project and should be limited.
Most jobs take between 10-14min to run so proposing we limit them at 20min and increase when needed.

FLUID-6537 Limit CI workflows to 20 minutes

---

demos/prefsFramework/index.html
src/framework/preferences/css/stylus/Enactors.styl
src/framework/preferences/js/SyllabificationEnactor.js
tests/framework-tests/preferences/html/SyllabificationEnactor-test.html
tests/framework-tests/preferences/js/SyllabificationEnactorTests.js

https://issues.fluidproject.org/browse/FLUID-6554

FLUID-6554: Handle soft hyphens in content

---

package.json
tests/bundle-tests/testem.js
tests/testem.js

I get a deprecation warning when running NPM install because the [gpii-testem](https://www.npmjs.com/package/gpii-testem) package has been migrated to [fluid-testem](https://www.npmjs.com/package/fluid-testem). This resolves the issue.

NOJIRA: migrate to fluid-testem package

---

package.json

Related to https://issues.fluidproject.org/browse/FLUID-6556, this PR updates the `engines` configuration in `package.json` to indicate that we only support Node >= 12.

NOJIRA: update engines to supported Node version

---

demos/prefsFramework/index.html
tests/manual-tests/framework/preferences/assortedContent/index.html

This PR addresses mixed content errors flagged by Netlify by removing (broken) insecure links to favicons on the NOAA website and updating a link to an image on the Fluid Project wiki to use SSL.

NOJIRA: fix mixed content errors

---

.codecov.yml

Extracted @jobara's change from 472133ecf5630d6f189c2bd26309492682bdfab3 so that we can get it merged independently and stop getting errors about patch coverage.

FLUID-6529: turn off coverage check for patches

---

.gitignore
Gruntfile.js
README.md
ReleaseNotes.md
examples/framework/preferences/captionsPreference/index.html
examples/framework/preferences/localizationPreference/urlPath/en/index.html
examples/framework/preferences/localizationPreference/urlPath/es/index.html
examples/framework/preferences/localizationPreference/urlPath/fa/index.html
examples/framework/preferences/localizationPreference/urlPath/fr/index.html
examples/framework/preferences/localizationPreference/urlPath/index.html
package.json
src/framework/preferences/preferencesDependencies.json
src/thirdPartyDependencies.json
tests/framework-tests/preferences/html/CaptionsEnactor-test.html

The URL api is now available in all of our supported browsers (https://caniuse.com/url) so I think it can safely be removed.

FLUID-6608: remove url-polyfill dependency

---

src/framework/preferences/js/Panels.js
tests/framework-tests/preferences/js/PanelsTests.js

This restores accessible labels to VoiceOver with Edge/Chrome on macOS. Should be tested on with Firefox on Windows using NVDA/JAWS to make sure it doesn't regress the behaviour that the `aria-label` was added to address.

FLUID-6619: announce contrast themes with VoiceOver/Edge

---

demos/textfieldControl/index.html
src/components/textfieldControl/css/TextfieldStepper.css
src/components/textfieldControl/js/TextfieldStepper.js
src/framework/preferences/css/sass/PrefsEditor.scss
src/framework/preferences/html/PrefsEditorTemplate-letterSpace.html
src/framework/preferences/html/PrefsEditorTemplate-lineSpace.html
src/framework/preferences/html/PrefsEditorTemplate-textSize.html
src/framework/preferences/html/PrefsEditorTemplate-wordSpace.html
tests/component-tests/textfieldControl/html/TextfieldStepper-test.html
tests/component-tests/textfieldControl/js/TextfieldStepperTests.js

This PR resolves [FLUID-6620](https://issues.fluidproject.org/browse/FLUID-6620) by updating the Textfield Stepper component throughout Infusion to a standard `<input type="number>` ([MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)). This resolves the perplexing behaviour in VoiceOver on Safari where announced values are represented as a decimal based on `aria-valuenow` / `aria-valuemax` for inputs with the `spinbutton` role instead of the displayed value (see: https://bugs.webkit.org/show_bug.cgi?id=221102).
The `number` input type has native `stepUp()` and `stepDown()` methods for incrementing and decrementing its value. It might be good to leverage these somehow instead of using the custom logic defined in `fluid.textfieldStepper.step`, but that's a …

FLUID-6620: convert Textfield Stepper to number input

---

tests/framework-tests/preferences/js/IntegrationTestsCommon.js
tests/framework-tests/preferences/js/SeparatedPanelPrefsEditorTests.js
tests/framework-tests/preferences/js/UIEnhancerTests.js

This is a blocker for Infusion 3.0
https://issues.fluidproject.org/browse/FLUID-6632

FLUID-6632: Fix tests failing in Safari

---

src/framework/preferences/css/sass/utils/_themes.scss

https://issues.fluidproject.org/browse/FLUID-6654
This change restores the previous behaviour of using the default selection highlighting when the theme doesn't explicitly set it. Another option was to use a custom set selection highlighting styles based on the contrast theme. For binary this would be an inversion of the foreground/background colours. However, Safari blends the selections background-colour with the background-colour of the text being highlighted. This results in a lower contrast ratio. Try highlighting the text in this [example](https://codepen.io/jobara/full/mdmVYqG) and notice how the background affects the selection background colour. In most cases the contrast is still quite high, although not the same. In the low contrast theme (light-grey-dark-grey) the contrast …

FLUID-6654: Use default selection highlighting when not set by theme

---

src/framework/core/js/DataBinding.js
src/framework/core/js/FluidView.js
src/framework/core/js/ModelTransformationTransforms.js
tests/framework-tests/core/html/FluidIoCView-test.html
tests/framework-tests/core/js/DataBindingTests.js
tests/framework-tests/core/js/FluidIoCViewTests.js

- suggested by work on rewriting TextFieldControls. Renamed dom.attrs to dom.attr for consistency with dom.class. Better validation for "target" of model relays. Permit transforming short-form relays from non-model sources. fluid.transform.parseClasses transform, and allow relay from constants.

FLUID-6697, FLUID-6698: Improvements to DataBinding for applications with materialised DOM binding

---

src/framework/core/js/FluidIoC.js
src/framework/core/js/FluidView.js
src/framework/core/js/NewViewSupport.js
src/framework/core/js/ResourceLoader.js
tests/framework-tests/core/js/FluidIoCViewTests.js
tests/framework-tests/core/js/NewViewSupportTests.js

FLUID-6703: Fix and test case for id materialisation precedence
FLUID-6704: Move priority of template fetch to after model resolution
FLUID-6706: Support synchronous template fetches

FLUID-6703, FLUID-6704, FLUID-6706: Fixes supporting prefs framework rewrite

---

src/framework/core/js/jquery.standalone.js

This PR updates the global scope detection code in jquery.standalone.js to support use within an AudioWorkletGlobalScope, which is a super-minimal environment that provides no references to the global scope at all.
I haven't included any tests for this fix, because AudioWorkletGlobalScope doesn't even provide a means to import or load scripts, so we'd have to prepare a specialized build just for this purpose, which would include a custom AudioProcessor class and wrap everything in an ES6 module. I did, however, confirm that all the current unit tests continue to pass.

FLUID-6764: Fix to jquery.standalone for use with AudioWorklets.

---

.github/ISSUE_TEMPLATE/config.yml

Updates the URLs presented when trying to create a new issue from the GitHub. This updates the URLs that changed when Atalassian products were moved to cloud hosting.

FLUID-6776: update URLs related to GitHub issue templates

---

src/framework/core/css/fluid.css
src/framework/preferences/css/sass/PrefsEditor.scss

The `.fl-hidden-accessible` class is used on the labels for choices within the UIO theme picker. This was causing the horizontal overflow issue described in FLUID-6772. Changing the `position` of these visually hidden labels to `relative` resolves the issue.

FLUID-6772: resolve horizontal overflow issue

---

.github/workflows/ci-build.yml
.github/workflows/ci-lint.yml
.github/workflows/ci-test.yml

Many of the workflows in use (e.g. `actions/checkout@v2`) are about to be deprecated. This PR updates them accordingly and configures the required token for `codecov/codecov-action@v5`. Also note that this PR is unable to switch to using the NPM caching provided by the `setup-node` action because the `package-lock.json` file is not committed to Git. We may want to reconsider this.

NOJIRA: (ci) replace deprecated workflows with current versions

---

src/framework/preferences/css/sass/Contrast.scss
src/framework/preferences/css/sass/Contrast_base.scss
src/framework/preferences/css/sass/PrefsEditor.scss
src/framework/preferences/css/sass/README.md
src/framework/preferences/css/sass/SeparatedPanelPrefsEditor.scss
tests/manual-tests/framework/preferences/baseStyles/css/styles.css
tests/manual-tests/framework/preferences/baseStyles/index.html
tests/manual-tests/shared/css/manualTests.css

- fixes bug where blocking theme didn't fully isolate the separate panel from contrast theme changes
- fixes bug where separated panel wasn't styled properly after preference changes when only the base styles are used
- refactored `.fl-inverted-color` styling to swap foreground/background instead of recreating all of the theme styling rules
- added:
-  `--fl-linkFgColor`
- `--fl-linkBgColor`
- `--fl-disabledFgColor`
- `--fl-disabledBgColor`
- deprecated:
- `--fl-linkColor`
- `--fl-disabledColor`
- sass (.scss) files
- Added manual test for using UIO with only base styles 
- Build site: https://github.com/fluid-project/build.fluidproject.org/pull/37
- Docs: https://github.com/fluid-project/infusion-docs/pull/313

FLUID-6782, FLUID-6771: fixes contrast themes with blocking theme and base styles

---

demos/prefsFramework/index.html
demos/uiOptions/index.html
examples/framework/preferences/fullPagePanelStyle/index.html
examples/framework/preferences/minimalFootprint/fullPage.html
examples/framework/preferences/minimalFootprint/html/prefsEditorPreview.html
examples/framework/preferences/minimalFootprint/index.html
src/components/tableOfContents/js/TableOfContents.js
tests/component-tests/tableOfContents/html/TableOfContents-test.html
tests/component-tests/tableOfContents/js/TableOfContentsTests.js
tests/component-tests/uiOptions/html/UIOptions-test.html
tests/framework-tests/preferences/html/Builder-test.html
tests/framework-tests/preferences/html/Enactors-test.html
tests/framework-tests/preferences/html/FullNoPreviewPrefsEditor-test.html
tests/framework-tests/preferences/html/FullPreviewPrefsEditor-test.html
tests/framework-tests/preferences/html/LocalizationPrefsEditor-test.html
tests/framework-tests/preferences/html/PageEnhancer-test.html
tests/framework-tests/preferences/html/SeparatedPanelPrefsEditor-test.html
tests/framework-tests/preferences/html/SeparatedPanelPrefsEditorResponsiveTestPage.html
tests/framework-tests/preferences/html/TestPreviewTemplate.html
tests/framework-tests/preferences/html/UIEnhancer-test.html
tests/manual-tests/framework/preferences/assortedContent/index.html
tests/manual-tests/framework/preferences/fullPage-schema/index.html
tests/manual-tests/framework/preferences/fullPage/index.html
tests/manual-tests/framework/preferences/shared/html/prefsEditorPreview.html

- Adds comments to highlight the ToC container in demos
- Changes the ToC to be a `<nav>` element
- Updates the code to label the ToC container which is now often going to be a `<nav>` element.

FLUID-5098: Identify ToC container in demos

---

src/framework/preferences/css/sass/Contrast_base.scss
tests/manual-tests/framework/preferences/baseStyles/css/styles.css

- Adds values for selection colours for all contrast themes
- Updates the baseStyles demo to make use of selection contrast values
_**NOTE:** Requires #1110; whose changes are currently included in this PR_

FLUID-6783: styling selection highlights in contrast themes
